<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE errores[
<!ELEMENT errores (ejercicio+)>
<!ELEMENT ejercicio (nombre, error*)>
<!ATTLIST ejercicio id ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT error (linea, descripcion)>
<!ATTLIST error fecha CDATA #REQUIRED>
<!ATTLIST error hora CDATA #REQUIRED >
<!ELEMENT linea (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
]>

<errores>
    <ejercicio id = "e5">
      <nombre>etiqueta5.xml</nombre>
      <error fecha = "14/02/2022" hora = "12:55">
        <linea>2</linea>
        <descripcion>DOCTYPE no declarado</descripcion>
      </error>

      <error fecha = "14/02/2022" hora = "12:15">
        <linea>3</linea>
        <descripcion>No hay etiqueta ciudad</descripcion>
      </error>

    </ejercicio>
    
    <ejercicio id = "e6">
        <nombre>etiqueta5.xml</nombre>
        <error fecha = "20/02/2022" hora = "16:15">
          <linea>2</linea>
          <descripcion>DOCTYPE no declarado</descripcion>
        </error>
  
        <error fecha ="20/02/2022" hora = "12:55">
          <linea>3</linea>
          <descripcion>No hay etiqueta ciudad</descripcion>
        </error>
  
      </ejercicio>

      <ejercicio id = "e7">
        <nombre>etiqueta6.xml</nombre>
        <error fecha = "20/02/2022" hora = "16:15">
          <linea>3</linea>
          <descripcion>DOCTYPE no declarado</descripcion>
        </error>
  
        <error fecha ="20/02/2022" hora = "12:55">
          <linea>3</linea>
          <descripcion>No hay etiqueta ciudad</descripcion>
        </error>
  
      </ejercicio>

  </errores>