<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personas [
    <!ELEMENT personas (persona)+>
    <!ELEMENT persona (nombre, tlf,tw*)>
    <!ATTLIST persona id ID #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT tlf (#PCDATA)>
    <!ELEMENT tw (#PCDATA)>
]>

<personas>
    <persona id ="Ricardo">
        <nombre>
            Ricardo Borriquero
        </nombre>
        <tlf>
            951345679
        </tlf>
    
    </persona>
    <persona id="eva">
        <nombre>Eva Risto</nombre>
        <tlf>955837659</tlf>
        <tw>@evaristo</tw>
    </persona>
</personas>
